_wandb:
    value:
        cli_version: 0.22.2
        e:
            gyshkzr8aw45idpkwfhnx6e8v7spclk1:
                codePath: Q1.py
                codePathLocal: Q1.py
                email: 142402007@smail.iitpkd.ac.in
                executable: D:\MTech DS\Mtech sem 3\MLOps\ass_5\Assignment5\.venv\Scripts\python.exe
                host: Kundans-PC
                os: Windows-10-10.0.26100-SP0
                program: D:\MTech DS\Mtech sem 3\MLOps\ass_5\Assignment5\Q1.py
                python: CPython 3.11.3
                root: D:\MTech DS\Mtech sem 3\MLOps\ass_5\Assignment5
                startedAt: "2025-10-13T14:06:32.265471Z"
                writerId: gyshkzr8aw45idpkwfhnx6e8v7spclk1
        m: []
        python_version: 3.11.3
        t:
            "3":
                - 13
            "4": 3.11.3
            "5": 0.22.2
            "8":
                - 3
            "12": 0.22.2
            "13": windows-amd64
